[env:esp32p4]
platform = espressif32
board = esp32-p4-function-ev-board
framework = espidf
monitor_speed = 115200
lib_deps =
    melexis/MLX90640 Driver@^1.0.3
build_flags =
    -DMLX90640_I2C_ADDR=0x33
    -DI2C_SDA_GPIO=22
    -DI2C_SCL_GPIO=23
    -DI2C_FREQ_HZ=400000
